language: python
python:
    - 2.7
install:
    - pip install tox
    - pip install coveralls
script:
    - tox
after_success: 
    coveralls
env:
    global:
        -ORC_ZD_API_URL='https://localhost/api/v2/'
        -ORC_ZD_EMAIL='noreply@zendesk.com'
        -ORC_ZD_AUTH_TOKEN='abc123'
